CREATE OR REPLACE PROCEDURE `SP_MUESTRA_GENERO`()
	SELECT * FROM TBL_GENEROS 
    
CALL SP_MUESTRA_GENERO

CREATE OR REPLACE PROCEDURE `SP_MUESTRA_ESTADO_CIVIL`()
	SELECT * FROM TBL_ESTADO_CIVIL 
    
CALL SP_MUESTRA_ESTADO_CIVIL

CREATE OR REPLACE PROCEDURE `SP_MUESTRA_SUCURSALES`()
	SELECT * FROM TBL_SUCURSALES
	
CALL SP_MUESTRA_SUCURSALES


CREATE OR REPLACE PROCEDURE `SP_MUESTRA_CARGOS`()
	SELECT * FROM TBL_CARGO_EMPLEADO

CALL SP_MUESTRA_CARGOS

CREATE OR REPLACE PROCEDURE `SP_MUESTRA_TITULACIONES`()
	SELECT * FROM TBL_TITULACIONES

CALL SP_MUESTRA_TITULACIONES

--SP INSERTA PERSONA
CREATE OR REPLACE PROCEDURE `SP_INSERTA_PERSONA`(IN NOMBRE_PERSONA VARCHAR(60), IN APELLIDO_PERSONA VARCHAR(60) ,IN ID_GENERO INT , IN ID_ESTADO_CIVIL INT , IN DNI VARCHAR(25) , IN FECHA_NACIMIENTO DATE , IN DIRECCION VARCHAR(150), IN TELEFONO VARCHAR(25), IN CELULAR VARCHAR(25))
	INSERT INTO TBL_PERSONAS
    (
        DNI,
        NOMBRE_PERSONA,
        APELLIDO_PERSONA,
        ID_GENERO,
        ID_ESTADO_CIVIL,
        FECHA_NACIMIENTO,
        DIRECCION,
        TELEFONO,
        CELULAR
   )
   VALUES 
   (
        DNI,
        NOMBRE_PERSONA,
        APELLIDO_PERSONA,
        ID_GENERO,
        ID_ESTADO_CIVIL,
        FECHA_NACIMIENTO,
        DIRECCION,
        TELEFONO,
        CELULAR
   );

CALL SP_INSERTA_PERSONA('Nombre 1','Apellido 1',1,1,'0801-0000-00000','2010-10-02','Direccion 1','2777-07-07','99999999');

-- SP INSERTA EMPLEADO QUE LLEVA CRUCE CON LA TABLA PERSONAS
CREATE OR REPLACE PROCEDURE `SP_INSERTA_EMPLEADO`(IN ID_SUCURSAL INT , IN ID_ESTATUS_EMPLEADO INT , IN ID_TITULACION INT , IN ID_CARGO_EMPLEADO INT , IN FECHA_CONTRATO DATE, IN CORREO_EMPLEADO VARCHAR(60),IN CLAVE_EMPLEADO VARCHAR(255) , IN OBSERVACIONES_EMPLEADO VARCHAR(150) ,IN FOTOGRAFIA_EMPLEADO VARCHAR(200))
	INSERT INTO `TBL_EMPLEADOS`(
        ID_EMPLEADO,
        ID_SUCURSAL,
        ID_ESTATUS_EMPLEADO,
        ID_TITULACION,
        ID_CARGO_EMPLEADO,
        FECHA_CONTRATO,
        CORREO_EMPLEADO,		
        CLAVE_EMPLEADO,
        OBSERVACIONES_EMPLEADO,
        FOTOGRAFIA_EMPLEADO
    ) 
	VALUES 
    (
        (SELECT (`AUTO_INCREMENT` - 1)  AS VALOR_ACTUAL FROM  INFORMATION_SCHEMA.TABLES
		WHERE TABLE_SCHEMA = 'DB-TELEFONIA' AND TABLE_NAME = 'TBL_PERSONAS'),
        ID_SUCURSAL,
        ID_ESTATUS_EMPLEADO ,
        ID_TITULACION ,
        ID_CARGO_EMPLEADO , 
        FECHA_CONTRATO ,
        CORREO_EMPLEADO , 				
        CLAVE_EMPLEADO , 
        OBSERVACIONES_EMPLEADO , 
        FOTOGRAFIA_EMPLEADO
   	);

CALL SP_INSERTA_EMPLEADO(1,1,1,3,NOW(),'test1@gmail.com','asd456','Excelente Especimen','undraw_male_avatar_323b.png');